from project_library_layer.credentials.credential_data import save_azure_blob_storage_connection_str
from project_library_layer.credentials.credential_data import save_azure_input_file_storage_connection_str
from project_library_layer.credentials.credential_data import save_azure_event_hub_namespace_connection_str

from project_library_layer.credentials.credential_data import save_watcher_checkpoint_storage_account_connection_str

save_watcher_checkpoint_storage_account_connection_str("DefaultEndpointsProtocol=https;AccountName=storageaccountrgai1a757;AccountKey=j4TYtRYwIDyUNL4lKXXIfYgCftrTbJPhPHC8i/j66XSf6s81ruCaQqDnjh5WDMjrqqc4hulvZ8wxcYQb8KfukA==;EndpointSuffix=core.windows.net")
save_azure_blob_storage_connection_str("DefaultEndpointsProtocol=https;AccountName=storageaccountrgai197de;AccountKey=o56dC8V4h6GmP1bin7a9NO0e6pUWTJrf/lzO3ogX1vFOTnodTCKbZp5VsRHfCSSHDLF8XqMKP0wDVi82eiaT7Q==;EndpointSuffix=core.windows.net")
save_azure_input_file_storage_connection_str("DefaultEndpointsProtocol=https;AccountName=inputfilestorage;AccountKey=u2jUt3DLgsPiZO8S7kZ1yk4B7FJ6gCtdTeckaige1AXTnyPA1zby1w0n6HUi/2cdOAoo5E1jXrEeofyI6UDtFw==;EndpointSuffix=core.windows.net")